### PR TITLE
Added information about priors

### PR DESCRIPTION
**Pull request by rezashr**
Added sampling from priors as the default during fitting models.
Added comments re gathering information about priors and visualizing them.

### CODE REVIEW

**Comment by rezashr** [comment]
Awesome. Priors are now explicitly defined as student's t with a scale of 10 and 3 degrees of freedom.

**Comment by rezashr** [comment]
As per Daniel's comment, priors of the 'b' coefficients are now explicitly student's t with 3 degrees of freedom and scale of 10.

**Comment by zenourn** [comment]
Thanks. Looks great. I've got a few other minor changes I'll make to this branch and then Michael can review for integration.

**Comment by m-macaskill** [comment]
Thanks @rezashr and @zenourn, I've made a commit where I integrate Reza's suggested changes and just change a bit of style.
The only change I nixed was automatic installation of the `papaja` package: I don't think analysis scripts should change a user's environment without their active consent (and there could be other CRAN packages that any given user might also be lacking, so it wouldn't have prevented all dependent issues anyway).

**Pull request merged**
